version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependency: "
      include: "scope"
    open-pull-requests-limit: 15